name: CI on pull requests

on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  approved:
    runs-on: self-hosted
    steps:
      - run: CI_DIR=/tmp/seapath-ci-${RANDOM}; mkdir $CI_DIR; cd $CI_DIR; git clone --depth 1 -b test-perso git@github.com:eroussy/ci-seapath.git ci; ci/build.sh $GITHUB_REF
